# Generated by Django 5.0.4 on 2024-05-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='filial_receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_receive', to='post.filial'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mass',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='volume',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
